### PR TITLE
Fix day tags

### LINKED ISSUE #217: [MOBILE] Day tags go over the message input
**Describe the bug**

Day tags go over the message input when scrolling a long list of messages.

**To Reproduce**
1. Go to the direct messages page.
2. Send a bunch of messages so that the page can scroll.
3. Scroll up, see the day tags going over the message input.

**Expected behavior**

Day tags should not be visible over the message input.

**Device (please complete the following information):**
 - Device: both iOS and Andrdoid
  - Version: 0.12.2

### PR DESCRIPTION
**Pull request by guillemcordoba**
Fixes https://github.com/dash-chat/dash-chat/issues/217

### CODE REVIEW

File: ui/src/routes/direct-chats/[agentId]/+page.svelte [hunk 1]
```diff
@@ -182,6 +189,50 @@
 		});
 	};
 
+	// Keep the bottom of the message list pinned to the visible area as the
```
Comment (jadehopepunk) [inline ui/src/routes/direct-chats/[agentId]/+page.svelte]: Seems ok for now, but eventually I think we want to pull this out of the page into some sort of utility class. Maybe a component that wraps the visible message area.

**Review by jadehopepunk — APPROVED** [review]

File: ui/src/routes/direct-chats/[agentId]/+page.svelte (hunk 1 above)
Comment (guillemcordoba) [reply ui/src/routes/direct-chats/[agentId]/+page.svelte]: Sorry, that commit was actually from another feature, I reverted the changes from this PR.
